### PR TITLE
qt5: 5.14.2 -> 5.15.0

### PR DESCRIPTION
**Pull request by nrdxp**
Not mergable in it's current form but I'm sure someone else wants an updated webengine.

### CODE REVIEW

**Comment by petabyteboy** [comment]
Thanks! I have been using this since a few days and everything seems to work fine. I am using a few Qt applications, but no Plasma, so that might be broken. Do you know what these metatypes that you disabled are used for? Whan I tried to package Qt 5.15 shortly after the release I was not successful with disabling it and somehow assumed most applications wouldn't run anyways.

**Comment by nrdxp** [comment]
I have no idea what metatypes do unfortunately. Seems they are brand new in 5.15. IIRC, I only disabled them because they were part of the qtdeclarative package, but the installPhase kept attempting to push them into the qtbase store path, which obviously caused the build to fail. I attempted to search for where I could change the path for this, in case they were important, but failed to find it, so just disabled it for now and it worked out.

I wasn't sure if you wanted to bump your current pr, or wait it to merge before bumping to 5.15, which is why I left it at that for now.

**Comment by petabyteboy** [comment]
The Qt 5.14.2 PR is now merged. The qutebrowser 1.3.1 update is merged as well. You can open a new PR for Qt 5.15 if you want. I'm unsure what we can do about this metatypes thingy, I have no idea how to properly integrate it, I tried and failed a few weeks ago (already failed with building it in the first place). But what you have achieved here is already very useful and I will probably run my own systems with these patches applied until they are upstreamed.

**Comment by reinhardt** [comment]
FWIW I've been running my machine (with qutebrowser) on this branch for about two weeks now as well and it's been working nicely. Thanks for the effort!

**Pull request closed without merging**
